import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useContext } from 'react'
import CustomCard from '../components/Card'
import { CardRow } from '../components/styledComponents'
import Title from '../components/Title'
import { AssetContext } from '../contexts/assetContext'

export default function Home() {
  const assets = useContext(AssetContext)
  const { homePageCards } = assets

  return (
    <div className={styles.container}>
      <Head>
        <title>SDB Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Title title="Stephen Broadhurst" />
        <CardRow>
          {homePageCards.map((card) => {
            return (
              <div style={{ margin: 25 }} key={card.name}>
                <CustomCard cardData={card} />
              </div>
            )
          })}
        </CardRow>
      </div>
    </div>
  )
}
